apiVersion: v1
kind: Service
metadata:
  name: main-api
  namespace: main-api
  labels:
    app: main-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "6000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: main-api
  ports:
  - name: http
    port: 6000
    targetPort: 6000
