apiVersion: apps/v1
kind: Deployment
metadata:
  name: aux-service
  namespace: aux-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aux-service
  template:
    metadata:
      labels:
        app: aux-service
    spec:
      imagePullSecrets:
        - name: ecr-creds
      containers:
      - name: aux-service
        image: 989419672395.dkr.ecr.eu-west-2.amazonaws.com/kantox/challenge:aux-service-latest
        imagePullPolicy: Always
        env:
        - name: AUX_VERSION
          value: "0.0.1"
        - name: AWS_REGION
          value: "eu-west-2"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SECRET_ACCESS_KEY
        ports:
        - containerPort: 5000
