apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: aux-service-stripprefix
  namespace: aux-service
spec:
  stripPrefix:
    prefixes:
      - /aux-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aux-service-ingress
  namespace: aux-service
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: aux-service-aux-service-stripprefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /aux-service
        pathType: Prefix
        backend:
          service:
            name: aux-service
            port:
              number: 5000
