apiVersion: v1
kind: Service
metadata:
  name: aux-service
  namespace: aux-service
  labels:
    app: aux-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: aux-service
  ports:
  - name: http
    port: 5000
    targetPort: 5000
