apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-api
  namespace: main-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-api
  template:
    metadata:
      labels:
        app: main-api
    spec:
      imagePullSecrets:
        - name: ecr-creds
      containers:
      - name: main-api
        image: 989419672395.dkr.ecr.eu-west-2.amazonaws.com/kantox/challenge:main-api-latest
        imagePullPolicy: Always
        env:
        - name: MAIN_VERSION
          value: "0.0.1"
        - name: AWS_REGION
          value: "eu-west-2"
        - name: AUX_URL
          value: "http://aux-service.aux-service.svc.cluster.local:5000"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SECRET_ACCESS_KEY
        ports:
        - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: main-api
  namespace: main-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "6000"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  selector:
    app: main-api
  ports:
  - port: 6000
    targetPort: 6000
    nodePort: 30002
